#This is for testing purposes only.
version: '3.6'

services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_PASSWORD: xDxDxDxD
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:6.2.3
    restart: always
    ports:
      - 6379:6379

volumes:
  postgres-volume:
    driver: local