CREATE TABLE ACCOUNTS(
                         ID SERIAL PRIMARY KEY,
                         NAME VARCHAR(50) NOT NULL
);

CREATE UNIQUE INDEX ACCOUNTS_NAME ON ACCOUNTS (NAME);

CREATE TABLE USERS(
                      ID SERIAL PRIMARY KEY,
                      IDENTIFIER VARCHAR(320) NOT NULL,
                      PASSWORD VARCHAR(60) NOT NULL
);

CREATE UNIQUE INDEX USERS_IDENTIFIER ON USERS (IDENTIFIER);

CREATE TABLE ACCOUNTS_USERS (
    ID SERIAL PRIMARY KEY,
    ACCOUNT_ID INT NOT NULL REFERENCES ACCOUNTS (ID),
    USER_ID INT NOT NULL REFERENCES USERS (ID),
    ROLE_ID INT NOT NULL REFERENCES ROLES (ID)
);


CREATE TABLE ROLES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

INSERT INTO ROLES (NAME) VALUES ('OWNER'), ('CONTRIBUTOR');

CREATE TABLE PROJECTS(
                         ID SERIAL PRIMARY KEY,
                         NAME VARCHAR(50) NOT NULL,
                         ACCOUNT_ID INT NOT NULL REFERENCES ACCOUNTS (ID)
);

CREATE INDEX PROJECT_ACCOUNT_ID ON PROJECTS (ACCOUNT_ID);

CREATE TABLE ENVIRONMENTS(
                             ID SERIAL PRIMARY KEY,
                             NAME VARCHAR(50) NOT NULL,
                             PROJECT_ID INT NOT NULL REFERENCES PROJECTS (ID),
                             USER_ID INT REFERENCES USERS (ID)
);

CREATE INDEX ENVIRONMENT_PROJECT_ID ON ENVIRONMENTS (PROJECT_ID);

CREATE TABLE FEATURE_FLAGS(
                              ID SERIAL PRIMARY KEY,
                              NAME VARCHAR(50) NOT NULL,
                              VALUE BOOL NOT NULL,
                              ENVIRONMENT_ID INT NOT NULL REFERENCES ENVIRONMENTS (ID)
);

CREATE UNIQUE INDEX FEATURE_FLAGS_ENVIRONMENT_ID ON FEATURE_FLAGS (NAME, ENVIRONMENT_ID);
